export const GET_PRODUCTS = '@CATALOG/GET_PRODUCTS';
export const ADD_TO_BASKET = '@CATALOG/ADD_TO_BASKET';
export const FETCHED_PRODUCTS = '@CATALOG/FETCHED_PRODUCTS';

export const UPDATE_ITEM_QUANTITY = '@CHECKOUT/UPDATE_ITEM_QUANTITY';
export const DELETE_ITEM_FROM_BASKET = '@CHECKOUT/DELETE_ITEM_FROM_BASKET';

export const GET_PROMO_CODE = '@PROMO_CODE/GET_PROMO_CODE';
export const APPLY_DISCOUNT = '@DISCOUNT/APPLY_DISCOUNT';